{{- if .Values.autoscaling.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "control-api.fullname" . }}
  labels:
    {{- include "control-api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ max (sub .Values.autoscaling.minReplicas 1) 1 }}
  selector:
    matchLabels:
      {{- include "control-api.selectorLabels" . | nindent 6 }}
{{- end }}
