import { z } from "zod";
import type { AgentDefinition, AgentRole, AgentPermission } from "./types";

export const agentConfigSchema = z.object({
  id: z.string().min(1),
  role: z.enum(["architect", "builder", "reviewer", "security", "qa", "docs"]),
  name: z.string().min(1),
  description: z.string().default(""),
  systemPrompt: z.string().default(""),
  permissions: z.array(z.enum(["read", "propose", "execute"])).default(["read", "propose"]),
  allowedPaths: z.array(z.string()).default(["**"]),
  forbiddenPaths: z.array(z.string()).default([]),
  model: z.string().default("gpt-5.4-mini"),
});

export const agentConfigsSchema = z.object({
  agents: z.array(agentConfigSchema),
});

export function parseAgentYaml(yamlContent: string): AgentDefinition[] {
  try {
    const yaml = parseSimpleYaml(yamlContent);
    const parsed = agentConfigsSchema.safeParse(yaml);
    if (!parsed.success) {
      console.warn("AgentConfig", "Invalid agent YAML:", parsed.error);
      return [];
    }
    return parsed.data.agents;
  } catch (err) {
    console.warn("AgentConfig", "Failed to parse agent YAML:", err);
    return [];
  }
}

function parseSimpleYaml(input: string): unknown {
  const lines = input.split("\n").filter((l) => !l.trimStart().startsWith("#") && l.trim());
  const result: Record<string, unknown> = {};
  let currentAgents: unknown[] = [];
  let currentAgent: Record<string, unknown> = {};
  let inAgents = false;

  for (const line of lines) {
    if (line.trim() === "agents:") {
      inAgents = true;
      continue;
    }
    if (inAgents) {
      if (line.trim().startsWith("- id:")) {
        if (Object.keys(currentAgent).length > 0) {
          currentAgents.push(currentAgent);
        }
        currentAgent = { id: line.split(":").slice(1).join(":").trim() };
      } else if (line.trim().startsWith("- ")) {
        if (Object.keys(currentAgent).length > 0) {
          currentAgents.push(currentAgent);
        }
        currentAgent = {};
      } else if (currentAgent && line.includes(":")) {
        const colonIdx = line.indexOf(":");
        const key = line.slice(0, colonIdx).trim();
        let value: unknown = line.slice(colonIdx + 1).trim();
        if (value === "" || value === "[]") {
          value = [];
        } else if (typeof value === "string" && value.startsWith("[")) {
          value = value.slice(1, -1).split(",").map((s) => s.trim().replace(/['"]/g, ""));
        }
        currentAgent[key] = value;
      }
    }
  }
  if (Object.keys(currentAgent).length > 0) {
    currentAgents.push(currentAgent);
  }
  if (currentAgents.length > 0) {
    result.agents = currentAgents;
  }
  return result;
}

export function generateAgentYaml(agents: AgentDefinition[]): string {
  const lines = ["# Agent Configuration", "# Generated by Oclushion", "", "agents:"];
  for (const agent of agents) {
    lines.push(`  - id: ${agent.id}`);
    lines.push(`    role: ${agent.role}`);
    lines.push(`    name: ${agent.name}`);
    lines.push(`    description: "${agent.description}"`);
    lines.push(`    model: ${agent.model}`);
    lines.push(`    permissions: [${agent.permissions.join(", ")}]`);
    lines.push(`    systemPrompt: |`);
    for (const pLine of agent.systemPrompt.split("\n")) {
      lines.push(`      ${pLine}`);
    }
    lines.push(`    allowedPaths: [${agent.allowedPaths.join(", ")}]`);
    if (agent.forbiddenPaths.length > 0) {
      lines.push(`    forbiddenPaths: [${agent.forbiddenPaths.join(", ")}]`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
