export type BrowserTab = {
  id: string;
  url: string;
  title: string;
  favicon?: string;
  isActive: boolean;
  isLoading: boolean;
  openedAt: string;
};

export type BrowserHistory = {
  url: string;
  title: string;
  visitedAt: string;
};

export type MockupElementType = "rectangle" | "text" | "image" | "button" | "input" | "container";

export type MockupElement = {
  id: string;
  type: MockupElementType;
  x: number;
  y: number;
  width: number;
  height: number;
  label?: string;
  color?: string;
  borderRadius?: number;
  children?: string[];
};

export type MockupBoard = {
  id: string;
  name: string;
  elements: MockupElement[];
  createdAt: string;
  updatedAt: string;
  linkedFiles?: string[];
};

export type ChatChannel = {
  id: string;
  name: string;
  type: "general" | "project" | "direct" | "ai-feed";
  members: string[];
  unreadCount: number;
};

export type NotificationSeverity = "low" | "medium" | "critical";

export type OSNotification = {
  id: string;
  severity: NotificationSeverity;
  title: string;
  message: string;
  timestamp: string;
  isRead: boolean;
  actionLink?: string;
  sourceUserId?: string;
};

export type NotificationSettings = {
  muteLow: boolean;
  muteMedium: boolean;
  
  adminWatchMode: boolean;
};

export type ChatMessage = {
  id: string;
  channelId: string;
  authorId: string;
  authorName: string;
  authorType: "human" | "agent";
  content: string;
  timestamp: string;
  attachments?: ChatAttachment[];
};

export type ChatAttachment = {
  type: "file" | "code-snippet" | "screenshot" | "diff";
  name: string;
  content: string;
};

export type LiveDoc = {
  id: string;
  title: string;
  filePath: string;
  content: string;
  autoGenerated: boolean;
  lastSyncedAt: string;
  linkedSourceFiles: string[];
  staleWarning?: string;
};

export type AnalyticsMetric = {
  name: string;
  value: number;
  unit: string;
  trend: "up" | "down" | "stable";
  sparkline: number[];
};

export type AnalyticsDashboard = {
  projectId: string;
  lastUpdated: string;
  metrics: AnalyticsMetric[];
  activeUsers?: number;
  errorRate?: number;
  p95Latency?: number;
};

export type OclushionOSSnapshot = {
  browser: {
    tabs: BrowserTab[];
    history: BrowserHistory[];
  };
  mockups: MockupBoard[];
  chat: {
    channels: ChatChannel[];
    recentMessages: ChatMessage[];
  };
  docs: LiveDoc[];
  analytics: AnalyticsDashboard | null;
  notifications: OSNotification[];
  notificationSettings: NotificationSettings;
};
