use crate::pipeline::pattern_matcher::PatternEntry;

pub struct InjectionPhrases;

impl InjectionPhrases {
    pub fn entries() -> Vec<PatternEntry> {
        vec![
            PatternEntry {
                id: "inj-001".into(),
                phrase: r"(?i)ignore\s+(all\s+)?(previous|above|prior)\s+(instructions|commands|directions|prompts|messages)".into(),
                severity: 0.95,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-002".into(),
                phrase: r"(?i)forget\s+(everything|all)\s+above".into(),
                severity: 0.90,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-003".into(),
                phrase: r"(?i)you\s+are\s+now\s+".into(),
                severity: 0.80,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-004".into(),
                phrase: r"(?i)system\s+override".into(),
                severity: 0.85,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-005".into(),
                phrase: r"(?i)\bDAN\b".into(),
                severity: 0.75,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-006".into(),
                phrase: r"(?i)this\s+is\s+a\s+test".into(),
                severity: 0.70,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-007".into(),
                phrase: r"(?i)print\s+(your|the)\s+(instructions|prompt|system\s+prompt|directions)".into(),
                severity: 0.85,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-008".into(),
                phrase: r"(?i)output\s+(your|the)\s+(system\s+)?prompt".into(),
                severity: 0.90,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-009".into(),
                phrase: r"(?i)from\s+now\s+on".into(),
                severity: 0.75,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-010".into(),
                phrase: r"(?i)(1gnore|1gn0re|ignore)\s+(all\s+)?(prev1ous|previous|pr3vious)\s+(1nstruct1ons|instructions|1nstruct10ns)".into(),
                severity: 0.85,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-011".into(),
                phrase: r"(?i)ignora\s+las\s+instrucciones\s+anteriores".into(),
                severity: 0.90,
                category: "injection".into(),
                languages: vec!["es".into()],
            },
            PatternEntry {
                id: "inj-012".into(),
                phrase: r"(?i)忽略之前的指示".into(),
                severity: 0.90,
                category: "injection".into(),
                languages: vec!["zh".into()],
            },
            PatternEntry {
                id: "inj-013".into(),
                phrase: r"(?i)игнорируйте\s+предыдущие\s+инструкции".into(),
                severity: 0.90,
                category: "injection".into(),
                languages: vec!["ru".into()],
            },
            PatternEntry {
                id: "inj-014".into(),
                phrase: r"(?i)disregard\s+(all\s+)?(previous|prior)\s+(instructions|commands)".into(),
                severity: 0.85,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-015".into(),
                phrase: r"(?i)new\s+(instructions|prompt|directive|order)\s*follow".into(),
                severity: 0.75,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-016".into(),
                phrase: r"(?i)repeat\s+(everything|all|the\s+above|your\s+prompt)".into(),
                severity: 0.80,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-017".into(),
                phrase: r"(?i)say\s+(everything|the\s+words|exactly)".into(),
                severity: 0.70,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-018".into(),
                phrase: r"(?i)reveal\s+(your|the)\s+(instructions|prompt|system\s+message)".into(),
                severity: 0.85,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-019".into(),
                phrase: r"(?i)act\s+as\s+(if\s+)?(you\s+are|your\s+(are|role\s+is))".into(),
                severity: 0.65,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-020".into(),
                phrase: r"(?i)simulate\s+(a\s+)?(shell|terminal|command|prompt)".into(),
                severity: 0.70,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-021".into(),
                phrase: r"(?i)hypothetical:\s*".into(),
                severity: 0.60,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-022".into(),
                phrase: r"(?i)do\s+not\s+(follow|obey|adhere\s+to)\s+(your\s+)?(instructions|rules|guidelines)".into(),
                severity: 0.80,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-023".into(),
                phrase: r"(?i)override\s+(your\s+)?(previous|system)\s+(instructions|directive|command)".into(),
                severity: 0.85,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-024".into(),
                phrase: r"(?i)你是一个".into(),
                severity: 0.75,
                category: "injection".into(),
                languages: vec!["zh".into()],
            },
            PatternEntry {
                id: "inj-025".into(),
                phrase: r"(?i)ignore\s+(the\s+)?(above|previous)\s+(and\s+)?(start|begin)\s+(a\s+)?new".into(),
                severity: 0.85,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-026".into(),
                phrase: r"(?i)start\s+(a\s+)?new\s+(chat|conversation|session)".into(),
                severity: 0.65,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-027".into(),
                phrase: r"(?i)inject(ed|ion)?\s*(:|instruction|command)".into(),
                severity: 0.70,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-028".into(),
                phrase: r"(?i)red\s+teaming".into(),
                severity: 0.60,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-029".into(),
                phrase: r"(?i)adversarial\s+(prompt|input|attack)".into(),
                severity: 0.65,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
            PatternEntry {
                id: "inj-030".into(),
                phrase: r"(?i)security\s+(bypass|circumvent|evade|get\s+around)".into(),
                severity: 0.80,
                category: "injection".into(),
                languages: vec!["en".into()],
            },
        ]
    }
}
