import type { AgentWorkspacePolicy } from "./types.js";

export const defaultWorkspacePolicy: AgentWorkspacePolicy = {
  maxFileBytes: 512 * 1024,
  blockedFileNames: [
    ".env",
    ".env.local",
    ".env.production",
    ".npmrc",
    ".pypirc",
    "id_rsa",
    "id_ed25519",
  ],
  blockedExtensions: [".pem", ".key", ".p12", ".pfx", ".sql", ".sqlite", ".db"],
  ignoredDirectories: [
    ".git",
    ".next",
    ".sano",
    "coverage",
    "dist",
    "node_modules",
    "playwright-report",
    "test-results",
  ],
  allowedCommands: [
    "bun",
    "cmd",
    "deno",
    "git",
    "node",
    "npm",
    "pnpm",
    "python",
    "python3",
    "tsx",
    "tsc",
  ],
  blockedCommands: [
    "curl",
    "docker",
    "docker-compose",
    "gh",
    "iwr",
    "Invoke-RestMethod",
    "Invoke-WebRequest",
    "nc",
    "netcat",
    "rm",
    "scp",
    "ssh",
    "wget",
  ],
  requireApprovalCommands: ["git push", "git tag", "npm publish", "pnpm publish"],
  allowedNetworkHosts: ["localhost", "127.0.0.1", "::1"],
  blockedToolNames: ["shell.unmediated", "browser.open_external", "mcp.raw"],
  requireApprovalToolNames: ["github.write", "filesystem.apply", "cloud.deploy"],
};
